apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: goacgras/auth
                  env:
                      # name of env variable
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                # name of the secret assign
                                name: jwt-secret
                                # name of the key assigned in secret
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    # by default iw will create clusterIp
    # type: clusterIp
    ports:
        - name: auth
          protocol: TCP
          port: 3000
          targetPort: 3000
