# run this when we merge PR to master
name: deploy-auth

on:
  # when we merge PR its count as push   
  push:
    branches:
      - master
    # it also run when there is changes in this path     
    paths:
      - 'auth/**'
jobs: 
  # name of the job   
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout all codes out of repo       
      - uses: actions/checkout@v2
      # run this command       
      - run: cd auth && docker build -t goacgras/auth .
      # login to docker before push
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push goacgras/auth
