name: tests-orders

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        #take all the codes
      - uses: action/checkout@v2
      - run: cd orders && npm install && npm run test:ci
