name: tests-tickets

on:
  pull_request:
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #take all the codes
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
